### ISSUE TITLE
Dados da pesquisa

### ISSUE THREAD

**Issue by planestepper** [internetlab-br/bots#2]
Estudando a API do Twitter, verifiquei que os IDs dos seguidores são retornados partindo do mais recente, o que fundamentalmente torna os dados diferentes do que foi usado na pesquisa. Em relação à reprodutibilidade da pesquisa, gostaria de pedir a disponibilização dos dados utilizados para a geração do relatório final. Vou além e gostaria de saber se o código que criou os gráficos da pesquisa também pode ser disponibilizado (ou se já está disponível).

**Comment by lagolucas** [comment]
Código que usei em R para fazer os gráficos não estão disponíveis porque foi só um comando plot, coloco eles assim que tiver acesso a ele, no momento não estou no computador que tem todos os códigos.

Vou ver com o pessoal se tudo bem liberar o banco de dados inteiro, acho que não tem problema. Assim que tiver um ok, coloco as duas coisas aqui e te dou um alô, pode ser?

**Comment by planestepper** [comment]
Perfeito!
